### ISSUE TITLE
Cannot run Downsampling script (submission failed)

### ISSUE THREAD

**Issue by keyvanelhami** [Clinical-Genomics/downsampling#5]
I get below error message when running on Hasta. I have no idea what the reason to this error is since it's first time for me running downsampling on Hasta. 

`[1|10|11] [keyvan.elhami@hasta: … oduction/bin] [P_main] $ sbatch --mem 100GB -n 2 -t 02:00:00 -A production -e /home/proj/production/cancer/cases/mintpossum_20M/down-%j.err -o /home/proj/production/cancer/cases/mintpossum_20M/down-%j.log downsample.sh /home/proj/production/cancer/cases/mintpossum/fastq/ /home/proj/production/cancer/cases/mintpossum_20M/fastq/ 20000000
sbatch: error: Batch job submission failed: Invalid account or account/partition combination specified`

**Comment by patrikgrenfeldt** [comment]
Do you have permission to submit jobs with sbatch?

**Comment by keyvanelhami** [comment]
Don't know, how can I check that?

**Comment by henrikstranneheim** [comment]
Are you part of "-A production" when you submit?

**Comment by keyvanelhami** [comment]
Nope: 

`[0|0|1156] [keyvan.elhami@hasta:~] [base] $ groups`
`users clinical-genomics hasta hasta-development hasta-cancer hasta-rare-disease`

**Comment by henrikstranneheim** [comment]
Then you can just change to "-A development"

**Comment by keyvanelhami** [comment]
Thank you, provlem solved. 

I will write a comment in the Downsampling doc in AM (1340:7) regarding the option of choosing "development" if you are not part of production.
